#!/bin/bash

set -e

export SHELL="/bin/bash"
export LC_ALL=C

export HOME=/usr/local
sudo mkdir -p $HOME
sudo chown 1000:1000 /usr/local

unset LD_LIBRARY_PATH
if [ ! -d /home/runner/work ]; then NTHREADS=$(( ($(grep -c processor /proc/cpuinfo) * 3 + 1) / 4)); else NTHREADS=$(grep -c processor /proc/cpuinfo); fi

curl -L https://gitweb.gentoo.org/repo/proj/prefix.git/plain/scripts/bootstrap-prefix.sh -o /tmp/bootstrap-prefix.sh
sed -i -z 's@sys-devel/patch\n\t\tsys-devel/binutils-config@sys-devel/patch\n\t\tsys-libs/zlib\n\t\tsys-devel/binutils-config@g' /tmp/bootstrap-prefix.sh
chmod 0755 /tmp/bootstrap-prefix.sh

EMERGE_DEFAULT_OPTS="--jobs 2" MAKEOPTS="--jobs ${NTHREADS}" /tmp/bootstrap-prefix.sh /usr/local/gentoo stage1
EMERGE_DEFAULT_OPTS="--jobs 2" MAKEOPTS="--jobs ${NTHREADS}" /tmp/bootstrap-prefix.sh /usr/local/gentoo stage2
sed -i "s@'-static' '-static-pie' '-fno-PIE -no-pie'@'-static'@g" /usr/local/gentoo/var/db/repos/gentoo/sys-devel/binutils/binutils-*.ebuild
for i in /usr/local/gentoo/var/db/repos/gentoo/sys-devel/binutils/*.ebuild; do j=$(basename $i); sed -i "s@EBUILD $j .*@EBUILD $j $(du -b $i | cut -f1) BLAKE2B $(b2sum $i | cut -d' ' -f1) SHA512 $(sha512sum $i | cut -d' ' -f1)@g" /usr/local/gentoo/var/db/repos/gentoo/sys-devel/binutils/Manifest; done
echo -e "EMERGE_DEFAULT_OPTS=\"--jobs 2\"\nMAKEOPTS=\"--jobs 2\"\nUSE=\"alsa dbus gtk harfbuzz -nls opengl openssl pulseaudio text vulkan wayland X\"" > /usr/local/gentoo/etc/portage/make.conf/make.conf
echo -e 'app-alternatives/ninja -reference samurai' > /usr/local/gentoo/etc/portage/package.use/dep_cycle_fix
EMERGE_DEFAULT_OPTS="--jobs 2" MAKEOPTS="--jobs ${NTHREADS}" USE="openssl" /tmp/bootstrap-prefix.sh /usr/local/gentoo stage3
rm /usr/local/gentoo/etc/portage/package.use/dep_cycle_fix

#rm /usr/local/gentoo/etc/portage/make.profile
#ln -s /usr/local/gentoo/var/db/repos/gentoo/profiles/default/linux/amd64/23.0/split-usr/no-multilib/prefix/kernel-3.2+ /usr/local/gentoo/etc/portage/make.profile
#/usr/local/gentoo/usr/bin/emerge -e @world app-portage/prefix-toolkit dev-cpp/gtest net-libs/libproxy net-misc/openssh

EMERGE_DEFAULT_OPTS="--jobs 2" MAKEOPTS="--jobs ${NTHREADS}" /usr/local/gentoo/usr/bin/emerge -uDN @world app-portage/prefix-toolkit dev-cpp/gtest net-libs/libproxy net-misc/openssh
ln -s libproxy/libpxbackend-1.0.so /usr/local/gentoo/usr/lib64/
mkdir /usr/local/bin
cp /usr/local/gentoo/startprefix /usr/local/bin/startprefix

#echo 'USE="alsa dbus gtk harfbuzz opengl openssl pulseaudio text udev vulkan wayland X"' >> /usr/local/gentoo/etc/portage/make.conf/make.conf
#/usr/local/gentoo/usr/bin/emerge -uDN @world media-video/pipewire x11-base/xorg-drivers x11-base/xwayland

rm -rf /usr/local/gentoo/tmp/* /usr/local/gentoo/var/cache/distfiles/*

/usr/local/bin/startprefix <<SOMMELIER
git clone -b main https://chromium.googlesource.com/chromiumos/platform2.git /tmp/cros_tools
cd /tmp/cros_tools
mkdir -p ./vm_tools/sommelier/out
cd ./vm_tools/sommelier/out
meson setup -Dprefix=/usr/local/gentoo -Dlibdir=/usr/local/gentoo/usr/lib64 -Dbuildtype=release -Dxwayland_path=/usr/local/gentoo/usr/bin/Xwayland -Dxwayland_gl_driver_path=/usr/local/gentoo/usr/lib64/dri ..
ninja
ninja install
cd /
rm -rf /tmp/cros_tools
SOMMELIER

echo '' > /usr/local/.finished

