#!/bin/bash

set -e

export SHELL="/bin/bash"
export LC_ALL=C

export HOME=/usr/local
sudo mkdir -p $HOME
sudo chown 1000:1000 /usr/local

unset LD_LIBRARY_PATH
if [ ! -d /home/runner/work ]; then NTHREADS=$(( $(grep -c processor /proc/cpuinfo) / 4 )); if [ ${NTHREADS} -lt 1 ]; then NTHREADS=1; fi; else NTHREADS=4; fi

curl -L https://gitweb.gentoo.org/repo/proj/prefix.git/plain/scripts/bootstrap-prefix.sh -o /tmp/bootstrap-prefix.sh
sed -i -z 's@sys-devel/patch\n\t\tsys-devel/binutils-config@sys-devel/patch\n\t\tsys-libs/zlib\n\t\tsys-devel/binutils-config@g' /tmp/bootstrap-prefix.sh
chmod 0755 /tmp/bootstrap-prefix.sh

time EMERGE_DEFAULT_OPTS="--jobs 2" MAKEOPTS="--jobs ${NTHREADS}" USE="-fortran -nls" /tmp/bootstrap-prefix.sh /usr/local/gentoo stage1
time EMERGE_DEFAULT_OPTS="--jobs 2" MAKEOPTS="--jobs ${NTHREADS}" USE="-fortran -nls" /tmp/bootstrap-prefix.sh /usr/local/gentoo stage2
echo -e "EMERGE_DEFAULT_OPTS=\"--jobs 2\"\nMAKEOPTS=\"--jobs 4\"\nVIDEO_CARDS=\"\"\nUSE=\"-llvm -nls\"" > /usr/local/gentoo/etc/portage/make.conf/make.conf
mkdir -p /usr/local/gentoo/etc/portage/package.use
echo -e "sys-devel/gcc cxx openmp -ada -d -fortran -go -jit -mpx -objc -objc++ -objc-gc" > /usr/local/gentoo/etc/portage/package.use/gcc
sed -i "s@'-static' '-static-pie' '-fno-PIE -no-pie'@'-static'@g" /usr/local/gentoo/var/db/repos/gentoo/sys-devel/binutils/binutils-*.ebuild
for i in /usr/local/gentoo/var/db/repos/gentoo/sys-devel/binutils/*.ebuild; do j=$(basename $i); sed -i "s@EBUILD $j .*@EBUILD $j $(du -b $i | cut -f1) BLAKE2B $(b2sum $i | cut -d' ' -f1) SHA512 $(sha512sum $i | cut -d' ' -f1)@g" /usr/local/gentoo/var/db/repos/gentoo/sys-devel/binutils/Manifest; done
time EMERGE_DEFAULT_OPTS="--jobs 2" MAKEOPTS="--jobs ${NTHREADS}" /tmp/bootstrap-prefix.sh /usr/local/gentoo stage3

EMERGE_DEFAULT_OPTS="--jobs 2" MAKEOPTS="--jobs ${NTHREADS}" /usr/local/gentoo/usr/bin/emerge -uDN @world app-portage/prefix-toolkit
mkdir /usr/local/bin
cp /usr/local/gentoo/startprefix /usr/local/bin/startprefix

rm -rf /usr/local/gentoo/tmp/* /usr/local/gentoo/var/cache/distfiles/*

echo '' > /usr/local/.finished

