#!/bin/bash

set -e

export SHELL="/bin/bash"
export LC_ALL=C

export HOME=/usr/local
sudo rm -rf $HOME
sudo mkdir $HOME
sudo chown 1000:1000 $HOME

curl -L $(curl -L -s https://api.github.com/repos/sebanc/chromeos-gentoo-prefix/releases/latest | grep browser_download_url | tr -d '"' | sed 's#browser_download_url: ##g') -o /tmp/chromeos-gentoo-prefix.tar.gz
tar zxf /tmp/chromeos-gentoo-prefix.tar.gz -C /usr/local

unset LD_LIBRARY_PATH
if [ ! -d /home/runner/work ]; then NTHREADS=$(( $(grep -c processor /proc/cpuinfo) / 4 )); if [ ${NTHREADS} -lt 1 ]; then NTHREADS=1; fi; else NTHREADS=4; fi

if [ ! -L /usr/local/gentoo/lib ]; then
	cp -r /usr/local/gentoo/lib/* /usr/local/gentoo/lib64/
	rm -r /usr/local/gentoo/lib
	ln -s lib64 /usr/local/gentoo/lib
fi
if [ ! -L /usr/local/gentoo/usr/lib ]; then
	cp -r /usr/local/gentoo/usr/lib/* /usr/local/gentoo/usr/lib64/
	rm -r /usr/local/gentoo/usr/lib
	ln -s lib64 /usr/local/gentoo/usr/lib
fi
rm /usr/local/gentoo/etc/portage/make.profile
ln -s /usr/local/gentoo/var/db/repos/gentoo/profiles/default/linux/amd64/17.0/no-multilib/prefix/kernel-3.2+ /usr/local/gentoo/etc/portage/make.profile

/usr/local/gentoo/usr/bin/emerge --sync --quiet
echo -e "EMERGE_DEFAULT_OPTS=\"--jobs 2\"\nMAKEOPTS=\"--jobs 4\"\nUSE=\"alsa dbus gtk harfbuzz -nls opengl openssl pulseaudio text vulkan wayland X\"" > /usr/local/gentoo/etc/portage/make.conf/make.conf
EMERGE_DEFAULT_OPTS="--jobs 2" MAKEOPTS="--jobs ${NTHREADS}" /usr/local/gentoo/usr/bin/emerge llvm-core/clang sys-libs/glibc dev-python/cython dev-build/cmake
#EMERGE_DEFAULT_OPTS="--jobs 2" MAKEOPTS="--jobs ${NTHREADS}" /usr/local/gentoo/usr/bin/emerge -uDN @world dev-cpp/gtest media-video/pipewire net-libs/libproxy net-misc/openssh x11-base/xorg-drivers x11-base/xwayland
rm -f /usr/local/gentoo/usr/lib64/libpxbackend-1.0.so
ln -s libproxy/libpxbackend-1.0.so /usr/local/gentoo/usr/lib64/

/usr/local/bin/startprefix <<SOMMELIER
git clone -b main https://chromium.googlesource.com/chromiumos/platform2.git /tmp/cros_tools
cd /tmp/cros_tools
mkdir -p ./vm_tools/sommelier/out
cd ./vm_tools/sommelier/out
meson setup -Dprefix=/usr/local/gentoo -Dlibdir=/usr/local/gentoo/usr/lib64 -Dbuildtype=release -Dxwayland_path=/usr/local/gentoo/usr/bin/Xwayland -Dxwayland_gl_driver_path=/usr/local/gentoo/usr/lib64/dri ..
ninja
ninja install
cd /
rm -rf /tmp/cros_tools
SOMMELIER

rm -rf /usr/local/gentoo/tmp/* /usr/local/gentoo/var/cache/distfiles/*

echo '' > /usr/local/.finished

